test: add lerna parallelism extension to the e2e script

diff --git a/.github/workflows/WebAutomatedTests.yml b/.github/workflows/WebAutomatedTests.yml
--- a/.github/workflows/WebAutomatedTests.yml
+++ b/.github/workflows/WebAutomatedTests.yml
@@ -12,33 +12,46 @@ jobs:
         name: "Automated tests"
         runs-on: ubuntu-latest
         permissions:
-          packages: read
-          contents: read
+            packages: read
+            contents: read
+        strategy:
+            # when one test fails, DO NOT cancel the other
+            fail-fast: false
+            matrix:
+                # run 3 copies of the current job in parallel
+                containers: [1, 2, 3]
 
         steps:
             - name: "Checking changed files"
               id: files
               uses: softprops/diffset@v1
-              if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
+              if:
+                  github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name ==
+                  github.repository
               with:
-                global_files: |
-                  !{packages/**/*,configs/e2e/*.json,detox/**/*}
-                not_atlas_native_files: |
-                  !packages/theming/atlas/src/**/native/**
+                  global_files: |
+                      !{packages/**/*,configs/e2e/*.json,detox/**/*}
+                  not_atlas_native_files: |
+                      !packages/theming/atlas/src/**/native/**
               env:
-                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
             - name: "Checking-out code"
               uses: actions/checkout@v2
               with:
                   submodules: false
             - name: "Fetching master to compare"
-              if: github.event_name == 'pull_request' && (steps.files.outputs.global_files == '' || github.event.pull_request.head.repo.full_name != github.repository)
+              if:
+                  github.event_name == 'pull_request' && (steps.files.outputs.global_files == '' ||
+                  github.event.pull_request.head.repo.full_name != github.repository)
               run:
-                  git fetch --no-tags --prune --depth=1 origin +refs/heads/${{ github.base_ref }}:refs/remotes/origin/${{ github.base_ref }}
+                  git fetch --no-tags --prune --depth=1 origin +refs/heads/${{ github.base_ref
+                  }}:refs/remotes/origin/${{ github.base_ref }}
             - name: "Defining environment variables"
               id: variables
               run:
-                  echo "::set-output name=arg::$(if [ "${{ steps.files.outputs.global_files }}" = "" ] && ${{ github.event_name == 'pull_request' }}; then echo '--since origin/${{ github.base_ref }}'; else echo ''; fi)"
+                  echo "::set-output name=arg::$(if [ "${{ steps.files.outputs.global_files }}" = "" ] && ${{
+                  github.event_name == 'pull_request' }}; then echo '--since origin/${{ github.base_ref }}'; else echo
+                  ''; fi)"
             - name: "Defining cache"
               uses: actions/cache@v2
               env:
@@ -51,17 +64,23 @@ jobs:
             - name: "Building package in production mode"
               run: npm run release -- ${{ steps.variables.outputs.arg }}
             - name: Login to GitHub Container Registry
-              if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
+              if:
+                  github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name ==
+                  github.repository
               uses: docker/login-action@v1
               with:
                   registry: ghcr.io
                   username: ${{ github.actor }}
                   password: ${{ secrets.GITHUB_TOKEN }}
             - name: "Executing E2E tests"
-              if: github.event_name == 'push' || steps.files.outputs.not_atlas_native_files != '' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository)
-              run: npm run test:e2e -- ${{ steps.variables.outputs.arg }}
+              if:
+                  github.event_name == 'push' || steps.files.outputs.not_atlas_native_files != '' || (github.event_name
+                  == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository)
+              run: CIRCLE_NODE_INDEX=(${{matrix.containers}}-1) npm run test:e2e -- ${{ steps.variables.outputs.arg }}
               env:
-                FORKED: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
+                  FORKED:
+                      github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name ==
+                      github.repository
             - name: "Fixing files permissions"
               if: failure()
               run: |
